# Generated by Django 5.0.3 on 2024-04-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='stats',
            new_name='status',
        ),
    ]
